# Generated by Django 2.1.7 on 2019-03-22 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Асп', 'Аспирант'), ('Асс', 'Ассистент'), ('Доц', 'Доцент'), ('Проф', 'Профессор')], max_length=127),
        ),
    ]
