# Generated by Django 2.1.7 on 2019-03-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190322_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
